---
- hosts: all
  become: yes
  tasks:
    - name: Instalação do Git na maquina controle
      ansible.builtin.apt:
        name: git
        state: present
    - name: Install apache httpd (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
